const data = {
  products: [
    {
      _id: "1",
      name: "Nike Trouser",
      category: "Trouser",
     image: "/images/pi1.jpg",
      price: 400,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "2",
      name: "Adidas Trouser",
      category: "Trouser",
      image: "/images/pi2.jpg",
      price: 300,
      brand: "Adidas",
      rating: 4.0,
      numReviews: 12,
      description: "high quality product",
    },
    {
      _id: "3",
      name: "Lacoste Trouser",
      category: "Trouser",
      image: "/images/pi3.jpg",
      price: 450,
      brand: "Lacoste",
      rating: 4.1,
      numReviews: 18,
      description: "high quality product",
    },
    {
      _id: "4",
      name: "Gucci Trouser",
      category: "Trouser",
     image: "/images/pi4.jpg",
      price: 500,
      brand: "Gucci",
      rating: 3.9,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "5",
      name: "Dior Trouser",
      category: "Trouser",
     image: "/images/pi5.jpg",
      price: 420,
      brand: "Dior",
      rating: 5.0,
      numReviews: 15,
      description: "high quality product",
    },
  ],
};
export default data;
